"""initial tables

Revision ID: aca3d2066d33
Revises: 
Create Date: 2026-07-23 18:33:15.363493

"""
from alembic import op
import sqlalchemy as sa


revision = 'aca3d2066d33'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hostname', sa.String(), nullable=False),
    sa.Column('ip', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_hostname'), 'devices', ['hostname'], unique=True)
    op.create_table('metric_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('cpu_pct', sa.Float(), nullable=True),
    sa.Column('ram_pct', sa.Float(), nullable=True),
    sa.Column('disk_pct', sa.Float(), nullable=True),
    sa.Column('net_in_kbps', sa.Float(), nullable=True),
    sa.Column('net_out_kbps', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_snapshots_device_timestamp', 'metric_snapshots', ['device_id', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_snapshots_device_timestamp', table_name='metric_snapshots')
    op.drop_table('metric_snapshots')
    op.drop_index(op.f('ix_devices_hostname'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
